version: '3.8'

services:
  # backend:
  #   build:
  #     context: ./Backend
  #     dockerfile: Dockerfile
  #   container_name: indicadores_backend
  #   # Monta la carpeta para desarrollo en caliente (opcional)
  #   volumes:
  #     - ./Backend:/app
  #   ports:
  #     - 9999:8000
  #   networks:
  #     - app_network

  frontend:
    build:
      context: ./Frontend/app-frontend
      dockerfile: Dockerfile
    container_name: indicadores_frontend
    # Monta la carpeta para desarrollo en caliente (opcional, si quisieras)
    # volumes:
    #   - ./Frontend/app-frontend:/app
    ports:
      - 4200:80
    # depends_on:
    #   - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
